### ISSUE TITLE
Checkin Known Issues

### ISSUE THREAD

**Issue by tlofgren** [tlofgren/CentralLibrarySystem#1]
Dropdown menus for item statuses don't update the database. Haven't yet solved the problem of keeping track of dropdown menus individually when they are created by the user entering in items.

**Comment by JohnHofer** [comment]
... ... That's... Interesting. I'll double check on change_status.

"it worked on my machine"... yesterday
   --  John

**Comment by JohnHofer** [comment]
Hey, checked on change_status and tested by manually changing the database.
It really does work
